apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: harbor.example.com/your-harbor-project/ecommerce-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "REPLACE_DB_HOST"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db_2"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
